#!/usr/bin/env bash
# This script installs Nginx, modifies its configuration to listen on port 8080
# Update packages and install Nginx
apt-get update -y
apt-get install nginx -y
ufw allow 'Nginx HTTP'

# Create a file with a specific string
echo "hello world" > /var/www/html/index.html

# Restart Nginx to apply changes (without using systemctl)
service nginx restart
