#!/usr/bin/env bash
# Script that configures a new Ubuntu machine to respect above requirements

sudo apt-get update
sudo apt-get install -y nginx

echo "Hello World!" | sudo tee /var/www/html/index.html
new_rule="server_name _;\n\trewrite ^\/redirect_me https:\/\/stackoverflow.com permanent;"
sudo sed -i "s/server_name _;/$new_rule/" /etc/nginx/sites-enabled/default

sudo service nginx restart
