#!/usr/bin/env bash
# Script that configures a new Ubuntu machine to respect above requirements

sudo apt-get update
sudo apt-get install -y nginx

echo "Hello World!" | sudo tee /var/www/html/index.html
new_rule="server_name _;\n\trewrite ^\/redirect_me https:\/\/stackoverflow.com permanent;"
sudo sed -i "s/server_name _;/$new_rule/" /etc/nginx/sites-enabled/default

echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
replacement="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t}"

# Update the Nginx configuration to use the custom 404 page
sudo sed -i "s/listen 80 default_server;/$replacement/" /etc/nginx/sites-enabled/default

# Restart Nginx to apply changes
sudo service nginx restart
