#!/usr/bin/env bash
# Script that configures a new Ubuntu machine to respect above requirements

# Install HAProxy
sudo apt-get update
sudo apt-get install -y haproxy

# Enable HAProxy to be started by the init script
sudo sed -i 's/ENABLED=0/ENABLED=1/g' /etc/default/haproxy

# Backup the default configuration file
sudo mv /etc/haproxy/haproxy.cfg{,.original}

# Create a new configuration file
sudo bash -c 'cat << EOF > /etc/haproxy/haproxy.cfg
global
    log 127.0.0.1 local2
    chroot      /var/lib/haproxy
    pidfile     /var/run/haproxy.pid
    maxconn 2000
    user haproxy
    group haproxy
    daemon
    stats socket /var/lib/haproxy/stats

defaults
    log     global
    mode    http
    option  httplog
    option  dontlognull
    retries 3
    option redispatch
    timeout connect  5000
    timeout client  10000
    timeout server  10000

listen appname 0.0.0.0:80
    mode http
    stats enable
    stats uri /haproxy?stats
    stats realm Strictly\ Private
	stats auth ubuntu:ubuntu_
    balance roundrobin
    option httpclose
    option forwardfor
    server 335154-web-01 52.3.245.73 check
    server 335154-web-02 18.204.20.55 check
EOF'

# Start the HAProxy service
sudo service haproxy start
