#!/usr/bin/env bash
# Script that configures a new Ubuntu machine to respect above requirements
sudo sed -i 's/listen 80 default_server;/listen 0.0.0.0:80 default_server;/' /etc/nginx/sites-enabled/default
sudo /etc/init.d/nginx restart > /dev/null 2>&1
sudo kill "$(ps -o pid= -C nginx | head -1)" > /dev/null 2>&1
