#!/usr/bin/env bash
#script that configures a new Ubuntu machine to respect above requirements
sudo sed -i 's/listen 80 default_server;/listen 0.0.0.0:80 default_server;/' /etc/nginx/sites-enabled/default
