#!/usr/bin/env bash
# This script is displaying "Best School" 10 times

best="Best School"
count=0
while [ $count -lt 10 ]
do
    echo "$best"
    if [ $count -eq 8 ]; then echo "Hi"; fi
    count=$((count + 1))
done
