#!/usr/bin/env bash
# Find the Gunicorn master process ID
PIDS=$(pgrep -f "gunicorn")

if [ -z "$PIDS" ]; then
        echo "Gunicorn process not found. Start Gunicorn first."
        exit 1
fi

for PID in $PIDS; do
	kill -HUP "$PID"
done

echo "Reload complete."
